### ISSUE TITLE
railsexpress patches won't apply on p448 and latest stable RVM  (1.21.20)

### ISSUE THREAD

**Issue by srobertjames** [skaes/rvm-patchsets#20]
Applying patch https://raw.github.com/skaes/rvm-patchsets/master/patches/ruby/1.9.3/p448/railsexpress/13-railsbench-gc-fixes.patch...................
Error running 'patch -F 25 -p1 -N -f -i /tmp/tmp.KS6QFKzsmCghFhvZHQ',
please read /usr/local/rvm/log/ruby-1.9.3-p448-railsexpress/1376062746_patch.apply.13-railsbench-gc-fixes.patch.log

$ cat /usr/local/rvm/log/ruby-1.9.3-p448-railsexpress/1376062746_patch.apply.13-railsbench-gc-fixes.patch.log
patching file gc.c
Hunk #1 FAILED at 108.
Hunk #2 succeeded at 312 (offset -9 lines).
Hunk #3 FAILED at 557.
Hunk #4 succeeded at 572 with fuzz 3 (offset -9 lines).
Hunk #5 FAILED at 604.
Hunk #6 FAILED at 643.
Hunk #7 succeeded at 593 (offset -111 lines).
Hunk #8 FAILED at 1536.
Hunk #9 FAILED at 1794.
Hunk #10 succeeded at 1299 with fuzz 3 (offset -620 lines).
Hunk #11 FAILED at 2547.
Hunk #12 FAILED at 2563.
Hunk #13 FAILED at 3048.
Hunk #14 succeeded at 2373 with fuzz 2 (offset -714 lines).
Hunk #15 succeeded at 2386 with fuzz 3 (offset -714 lines).
Hunk #16 FAILED at 3150.
Hunk #17 FAILED at 3437.
11 out of 17 hunks FAILED -- saving rejects to file gc.c.rej

$ cat /etc/redhat-release 
CentOS release 6.3 (Final)

$ rvm -v

rvm 1.21.20 (stable) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]

**Comment by thomasbaustert** [comment]
I head the same issue and could fix it.
I run "rvm install 2.2.3 --patch railsexpress -n railsexpress" and got "Patch railsexpress not found". 

I run "rvm get stable" and still got the error.
But .rvm/patchsets/ruby/ only includes 2.2.1 as latest ruby.

I run "rvm get head" and .rvm/patchsets/ruby/ includes 2.2.3 as latest ruby.
I run "rvm install 2.2.3 --patch railsexpress -n railsexpress" and it works.

**Comment by SebiTimeWaster** [comment]
"rvm get head" also made it work for me with "rvm install 2.5.0 --patch railsexpress". 
Friendly XING greetings!
