### ISSUE TITLE
GC.enable_stats return value can be a bit misleading

### ISSUE THREAD

**Issue by kgrz** [skaes/rvm-patchsets#37]
```ruby
irb(main):003:0> GC.stats_enabled?
=> false
irb(main):005:0> GC.enable_stats
=> false
irb(main):006:0> GC.enable_stats
=> true
irb(main):007:0> GC.stats_enabled?
=> true
```

Shouldn't I expect the first call to `enable_stats` to return `true`?

**Comment by skaes** [comment]
Well, I have designed the interface so that it to corresponds to the behavior of GC.enable.

See http://www.ruby-doc.org/core-2.2.0/GC.html#method-c-enable
