### ISSUE TITLE
Memory usage NaN - 2.1.x

### ISSUE THREAD

**Issue by arr-dev** [skaes/rvm-patchsets#38]
I've compiled both MRI 2.1.0 and 2.1.5 with rvm 1.26.10 and still ruby-prof displays memory and allocation as NaN.

I've reinstalled ruby-prof after compilation.

There are no errors during compilation.

OS is Ubuntu 14.04.1 with ZSH 5.0.2.

**Comment by favrik** [comment]
Did you solve it @arr-dev ?    (same Ubuntu version)

**Comment by favrik** [comment]
FYI: moved to 2.0.0 and it worked.

**Comment by skaes** [comment]
Can you provide a reproducible test case?

Also: did you try both patched and unpatched versions?

And which ruby-prof version did you use?

**Comment by arr-dev** [comment]
@favrik thanks, haven't tried that, maybe it will work for me too
@skaes yes, both versions. Latest ruby-prof, 0.15.3.

**Comment by skaes** [comment]
@arr-dev well, if both patched and unpatched versions of MRI 2.1.5 show the same behavior, then why do you think reporting an issue here is going to help solve the problem?

**Comment by skaes** [comment]
oh, nevermind, the unpatched version won't be able to report memory usage at all.

sorry for the confusion.

**Comment by arr-dev** [comment]
Yeah :)
No worries.

**Comment by skaes** [comment]
it's not a patchset bug. I forgot to update ruby-prof to use the new standard methods for measuring memory and object allocations.

**Comment by skaes** [comment]
fixed in ruby-prof version 0.15.4

**Comment by arr-dev** [comment]
Awesome, thanks
