### ISSUE TITLE
2.2.2 Patchset Regression

### ISSUE THREAD

**Issue by felixbuenemann** [skaes/rvm-patchsets#39]
There's a regression in 2.2.2p133 (railsexpress) compared to vanilla 2.2.2p95:

```ruby
# ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
def foo fn, options, &block; end
=> :foo
foo -> {}, foo: :bar do; end
=> nil
# ruby 2.2.2p133 (2015-06-12 revision 50295) [x86_64-darwin15]
def foo fn, options, &block; end
=> :foo
foo -> {}, foo: :bar do; end
SyntaxError: unexpected keyword_do, expecting end-of-input
# workaround:
foo -> {}, { foo: :bar } do; end
=> nil
```

I'll try to find out which patch is causing this issue.

**Comment by felixbuenemann** [comment]
This also affects ruby-head, I'll try digging through the ruby-lang issue tracker.

**Comment by felixbuenemann** [comment]
I've opened https://bugs.ruby-lang.org/issues/11389. Feel free to close this issue if you think it's off topic here.

**Comment by felixbuenemann** [comment]
The regression is caused by the backport of the fix for [issue 11107](https://bugs.ruby-lang.org/issues/11107) in commit ruby/ruby@3dd4b24.

**Comment by skaes** [comment]
Thx for informing me. It has been fixed on 2.2-head How important is this for you to get fixed?

**Comment by felixbuenemann** [comment]
I think we can wait until the fix gets merged back into the ruby_2_1 and ruby_2_2 branches. I can just add the diff of 51350 on top of railsexpress in the meantime.

This bug is likely to crop up in rails when using custom finders on associations:
```ruby
  has_many :folders, -> { descendant_order }, inverse_of: :project do
    def find_by_param(param)
      find_by(type: "Folder::#{param.camelize}")
    end
    def find_by_param!(param)
      find_by!(type: "Folder::#{param.camelize}")
    end
  end
```

**Comment by felixbuenemann** [comment]
Btw. if someone else needs this fix ASAP this works:
```bash
rvm reinstall ruby-2.2 --patch railsexpress --patch https://github.com/ruby/ruby/commit/dfec9d978804fbd53df9e6b93e5801985b2b3130.diff
```

**Comment by skaes** [comment]
I think I will add the patch. After all, 2.2.2p95 does not exhibit the bug, so some people might think the railsepxress patches introduced it, and I don't want that to happen ;)

**Comment by felixbuenemann** [comment]
Sounds good, if you like I can create a PR.

**Comment by skaes** [comment]
thx, but I'll rather do it myself. I'm so used to using stgit locally do manage all my changes on top of the ruby repo that it would actually be more work for me to reverse my workflow.

**Comment by felixbuenemann** [comment]
#40 as a quick reminder what needs to be done. Feel free to roll your own version. There's also a couple of new backports in the ruby_2_2 branch, but this one is still missing.

**Comment by felixbuenemann** [comment]
Thanks!

**Comment by skaes** [comment]
thank you!
