### ISSUE TITLE
Ruby 3.0.3 Patch Request

### ISSUE THREAD

**Issue by sempervictus** [skaes/rvm-patchsets#46]
RVM currently has 3.0.3 available, but the last patch version in this repo is 3.0.2. Could you please forward-port the patch at some point to the current release?

**Comment by skaes** [comment]
@sempervictus thx for the hint. I wasn't aware of the new version.

**Comment by skaes** [comment]
@sempervictus https://github.com/rvm/rvm/pull/5167
